# Generated by Django 4.2.7 on 2023-11-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_inn_customuser_passport_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='passport_id',
            new_name='inn',
        ),
    ]
