# Generated by Django 4.2.7 on 2023-11-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_passport_id_customuser_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inn_org',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='org_name',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('org', 'First'), ('sup', 'Second')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
